### ISSUE TITLE
Add `with_view_data()` to pass data in the Django template and not to Inertia

### ISSUE THREAD

**Issue by girardinsamuel** [girardinsamuel/django-inertia#4]

**Comment by muarachmann** [comment]
@girardinsamuel could you please explain more on this? usage and what you plan to achieve here?

**Comment by girardinsamuel** [comment]
Yes of course !
Using the example from the README:
```python
from django_inertia import Inertia

def event_detail(request, id):
    event = Event.objects.get(pk=id)
    props = {
        'event': {
            'id':event.id,
            'title': event.title,
            'start_date': event.start_date,
            'description': event.description
        }
    }
    return Inertia.render(request, "Event/Show", props)
```

Here `props` is the context dictionnary that will be passed to the `Event/Show.vue` Vue component.

What if in the django .html template where this component is rendered you want to pass context (as in a normal django view) ? Right you cannot. So the idea is to chain a `with_view_data()` method to pass context to the django template instead of the Vue component.

The previous example would become:
```python
from django_inertia import Inertia

def event_detail(request, id):
    event = Event.objects.get(pk=id)
    props = {
        'event': {
            'id':event.id,
            'title': event.title,
            'start_date': event.start_date,
            'description': event.description
        }
    }
    context = {"key": "value"}
    return Inertia.render(request, "Event/Show", props).with_view_data(context)
```
Now the `app.html` would receive a `key` variable:

```html
<!-- app.html -->
{% load inertia_tags %}
<!DOCTYPE html>
<html  class="h-full bg-gray-200">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <script src="{{ STATIC_URL}}dist/app.js" defer></script>
    <link href="{{ STATIC_URL}}dist/app.css" rel="stylesheet" />
  </head>
  <body>
    <p>{{ key }}</p>
    {% inertia %}
  </body>
</html>
```

**Comment by muarachmann** [comment]
Thanks @girardinsamuel could I take on this?

**Comment by girardinsamuel** [comment]
Yes of course 🙏, feel free to open a PR !

Make sure to add a unit test for this if you can, and feel free to ask for help if needed 😉

**Comment by muarachmann** [comment]
> Owner

Also just wanted to say great work with the Masonite framework. Definitely digging this

**Comment by muarachmann** [comment]
@girardinsamuel as per our discussion on discord on agreeing to pass the `view_data` as extra argument. 
However there is a challenge if one of the key props passed is `page` how do we handle this in this case?  e.g
```
view_data = {'page': 'My best page'}
```
Merging this with the original context might override. Is that the behaviour we want?

**Comment by girardinsamuel** [comment]
No we don't want that. We could warn the user in the documentation that `page` is a reserved keyword.
We could also in the function, remove this key to ensure it does not override original context !

**Comment by girardinsamuel** [comment]
And maybe to improve this, we could rename the variable `page` to `__page`. Less chance that this one can be used.

This could also be a Django settings: `INERTIA_PAGE_CONTEXT="__page"` so that the user can change it,if he wants.

**Comment by muarachmann** [comment]
> And maybe to improve this, we could rename the variable `page` to `__page`. Less chance that this one can be used.
> 
> This could also be a Django settings: `INERTIA_PAGE_CONTEXT="__page"` so that the user can change it,if he wants.

Thanks for your input @girardinsamuel will work on this.
