### ISSUE TITLE
Generated value for data-page not JSON-parsable

### ISSUE THREAD

**Issue by mujahidfa** [girardinsamuel/django-inertia#7]
Got this error:
```
Uncaught (in promise) SyntaxError: Unexpected token ' in JSON at position 1
    at JSON.parse (<anonymous>)
    at exports.createInertiaApp (index.js?4bf4:1:9213)
    at eval (app.js?5e94:7:17)
    at Module../demo/static/src/app.js (app.js:455:1)
    at __webpack_require__ (app.js:797:42)
    at app.js:861:37
    at app.js:863:12
```

I believe this is because the generated `data-page` attribute string:
```html
<div id="app" data-page="{'component': 'Dashboard/Index', 'props': {'errors': False, 'success': False}, 'url': '/', 'version': '1'}"></div>
```
 is **not** valid JSON, hence the error. 

Valid JSON should be:
- double quotes, not single quotes 
- `False` is not a valid keyword in JSON, but `false` is (with a lower cap "f")

Below is a screenshot of the error:
![image](https://user-images.githubusercontent.com/17759705/167232041-966e0f68-e93b-41f7-8efb-d42a7c031c68.png)

No errors after manually editing the generated `data-page` attribute string to a valid JSON string:

![image](https://user-images.githubusercontent.com/17759705/167232301-73813b94-5822-4882-8324-d0473e19feec.png)

**Comment by girardinsamuel** [comment]
How did you got this error ? Did you use the template tag ?

**Comment by mujahidfa** [comment]
Yes, I did. The template tag is what generated the div element with the invalid JSON.
